
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product
              uri: lb://product
              predicates:
                - Path=/api/products/**

            - id: warehouse
              uri: lb://warehouse
              predicates:
                - Path=/api/warehouse/**

            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/api/transfers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port : 8080

