spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/product
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port:
    8099
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
jwt:
  secret: "my-super-secure-256-bit-secret-key-for-jwt-authentication"


